// Generated by CoffeeScript 1.5.0
(function() {
  var __slice = [].slice;

  define(function() {
    var Logger;
    return Logger = (function() {

      function Logger() {}

      Logger.delimiter = '::';

      Logger.setConsole = function(console) {
        this.console = console;
        return this;
      };

      Logger.log = function(messages) {
        var _ref;
        if ((this.console != null) && (this.console.log != null)) {
          return (_ref = this.console.log).call.apply(_ref, [this.console].concat(__slice.call(messages)));
        }
      };

      Logger.info = function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        args.unshift("INFO " + this.delimiter);
        return this.log(args);
      };

      return Logger;

    })();
  });

}).call(this);
